### ISSUE TITLE
Test cases don't inherit test suite labels

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#1005]
**Describe the bug**
Test cases don't inherit test suite labels

**To Reproduce**
Given there is a folder with the "root" name
Given there is a label with the name "label-test-suite" and scope: test suite, test case
Given there is a label with the name"label-test-case" and scope: test case

Create a test suite called "Create test case" in the "root" folder
Create a couple of test cases within "Create test case" 
Assign the "label-test-case" to the TestCase1
Assign the "label-test-suite" to the "Create test case" test suite
<img width="969" alt="image" src="https://github.com/testomatio/app/assets/5860505/bea05043-f9fd-4dc4-857f-bb1ebde9df66">

Open test case from the "Create test case" test suite
Observe test case has both labels: test suite and test case scope
<img width="1253" alt="image" src="https://github.com/testomatio/app/assets/5860505/240e44ea-bda1-405d-8bbc-53e3990dc67f">

Create a new test suite called "Move test case" in the root folder
Create a new test case called "Test Case 1 Move" in the "TestSuiteMove" test suite
<img width="650" alt="image" src="https://github.com/testomatio/app/assets/5860505/a0dea62c-03f7-43ab-8ac4-0cb08f9db289">

Move the test case "Test Case 1 Move" from "Move test case" test suite into "Create test case"
Observe
Test case moved 
<img width="975" alt="image" src="https://github.com/testomatio/app/assets/5860505/ee5d8b9c-da29-4a15-af73-8f0960c02f41">
Open "Test Case 1 Move"

**Actual**
Test case doesn't have "label-test-suite"
<img width="624" alt="image" src="https://github.com/testomatio/app/assets/5860505/554c648c-b025-41e9-bac5-2693ad5e2727">

<img width="970" alt="image" src="https://github.com/testomatio/app/assets/5860505/407166fb-c886-4e45-8188-01275bad858c">

**Expected**
Test case inherits test suite label

**Comment by littlefrontender** [comment]
backend issue

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! Thanks for reporting the issue. It was fixed. The fix will be published in the upcoming release. 

https://github.com/testomatio/app/assets/77803888/4235b24a-69f1-4b20-be1d-05d82b3e2fb4

**Comment by tikolakin** [comment]
Hi @TetianaKhomenko thanks for the fix
But it's not entirely fixed. When you move tests with modal window
labels are not inherited...
<img width="836" alt="image" src="https://github.com/testomatio/app/assets/5860505/ec827856-4be9-4677-97ba-61f3424c024b">
