### ISSUE TITLE
Test ID Case Sensitivity Issue During Import

### ISSUE THREAD

**Issue by BorshchOleksandr** [testomatio/app#1012]
**Describe the bug**
When importing tests, the test IDs are automatically converted to lowercase, causing discrepancies and errors. For instance, @ Sb2... becomes @ sb2 upon import, leading to issues in test identification and execution.

**To Reproduce**

1. Prepare a test file with test IDs in mixed case (e.g., @Sb2...).
2. Import the test file into Testomat.

**Expected behavior**
Test IDs should retain their original case, ensuring accurate identification and execution.

**Screenshots**
![Screenshot 2024-05-27 at 14 08 51](https://github.com/testomatio/app/assets/95282341/2a2059d8-af11-4f7f-af1e-8017fe2fe393)
<img width="1006" alt="Screenshot 2024-05-27 at 14 30 42" src="https://github.com/testomatio/app/assets/95282341/e168f14a-ea76-4ff0-b409-f7f9d17b6ec3">
<img width="1007" alt="Screenshot 2024-05-27 at 14 31 06" src="https://github.com/testomatio/app/assets/95282341/6f50e1f4-dba1-433e-8f0a-7a8e2abcc546">

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]
 - Application: [production or beta] 

**Additional context**

**Comment by BorshchOleksandr** [comment]
There is the following assumption:

If a number follows @S, the usual test is matched.
If a symbol follows @S, the user test is not matched and the first S is displayed as lowercase s.

<img width="908" alt="image" src="https://github.com/testomatio/app/assets/95282341/7ad4ae04-58ff-4c7a-86b0-d74ea98dd647">

**Comment by DavertMik** [comment]
@BorshchOleksandr  Thanks for the detailed info 

Please try version 1.4.3  I have fixed 

```
@testomatio/reporter@1.4.3
```

**Comment by BorshchOleksandr** [comment]
@DavertMik 
Thank you, your fix helped resolve the problem with 98% of the tests matching.

However, as I understand, there is still an issue as follows:

When we want to match tests for the second level of nesting, for example, Wallet, TimeLog, or Rise, you can look at our structure in the image.



In this case, the matching does not work based on the Test Suite ID.


![image](https://github.com/testomatio/app/assets/95282341/01ccebbe-39b1-4b5b-8bb9-ce9797ca3935)


![image](https://github.com/testomatio/app/assets/95282341/c1dcc0bb-4257-48df-8072-f868e0935275)


![image](https://github.com/testomatio/app/assets/95282341/c4b1b91b-fcd1-495f-a32c-c6c7209c751d)
![image](https://github.com/testomatio/app/assets/95282341/41d4f980-4f7e-4b28-aa87-e35c74b793e5)
![image](https://github.com/testomatio/app/assets/95282341/1e18606c-44f7-417d-b9c4-98bd88cda6de)

**Comment by BorshchOleksandr** [comment]
I also noticed that after your last fix, everything in the test name after the parentheses is not considered (it gets cut off) and does not appear in Testomatio.

For example, this did not appear in Testomatio:

(e.g. support@my-example.net)
(e.g. user@example-domain.co)
(e.g. test@)

etc.


![image](https://github.com/testomatio/app/assets/95282341/e94a5a04-7c05-4b80-8d18-fbbfe02413bb)

![image](https://github.com/testomatio/app/assets/95282341/e9379c2c-f415-47a0-afba-f7b680bf99d6)

**Comment by TetianaKhomenko** [comment]
@DavertMik have you seen the latest details?

**Comment by trumenov** [comment]
Can you please say what framework did you use for catch this bug? Or maybe you can send example xml file with this bug please.

I check in few frameworks - maybe this bug was already fixed in last releases...
![image](https://github.com/user-attachments/assets/37ab4f3f-aca1-4f23-9fb7-2fa4a6dd8911)

**Comment by DavertMik** [comment]
@BorshchOleksandr could you re-check this again? Does the issue still present?

**Comment by TetianaKhomenko** [comment]
Closing as done due to user's response.
