### ISSUE TITLE
Search doesn't show new suite when moving tests

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#1177]
**Describe the bug**
Tests can't be moved to newly created suite with multiselection.

**To Reproduce**
1. open a project
2. create a new suite
3. enable multiselect
4. select few tests
5. click Move button on the bottom bar
6. type newly created suite title
7. see no results shown

**Expected behavior**
Move pop-up search shows newly created suites when entering the title.

**Screenshots**

https://github.com/user-attachments/assets/79f8e9c3-2bb1-40ce-9402-400f06545ddb

**Comment by trumenov** [comment]
cant reproduce, maybe already fixed, or maybe some other keyboard layout was used (mean Ukranian 'р' != English 'p')... or meilisearch problems in production env...

**Comment by TetianaKhomenko** [comment]
re-checked on beta, the issue is still present attaching a video 

https://github.com/user-attachments/assets/dbd19eb9-2334-48bb-ab61-b271d508862d

**Comment by TetianaKhomenko** [comment]
The issue is still present. I suggest adding it to the earlier milestone since it's been reported by users few times already.

**Comment by DavertMik** [comment]
We need to update to Meilisearch 1.2, speed is announced to be 2x for indexing new data

Alternative approach is to store data for indexing in Redis for TTL < 10m
And append this to search

**Comment by TetianaKhomenko** [comment]
fixed!

**Comment by TheZZ13** [comment]
@TetianaKhomenko Can you please let me know when this ticket will be in the next build? I am still seeing it on my end.

**Comment by TetianaKhomenko** [comment]
Hi @TheZZ13! We are working on fixing this issue. Hopefully, it will be fixed this week. I re-open this ticket for now.

**Comment by TetianaKhomenko** [comment]
HI @TheZZ13! The fixed was published on the production.
