### ISSUE TITLE
Keep getting timeouts when using the search / search also doesn't load exact matches at the top of the search

### ISSUE THREAD

**Issue by vhd-lewis** [testomatio/app#1230]
**Describe the bug**
Keep getting timeouts when using the search / search also doesn't load exact matches at the top of the search

**Expected behavior**
No timeouts and also that searches with the exact match load that result at the top

**Screenshots**

<img width="718" alt="Image" src="https://github.com/user-attachments/assets/6fd30b32-e057-413f-983e-47b67fe9c637" />

**Comment by TetianaKhomenko** [comment]
Hi @vhd-lewis! The issue should be fixed now. Could you please check it on your project? thanks

**Comment by TetianaKhomenko** [comment]
The issue was re-tested and verified as fixed.

**Comment by vhd-lewis** [comment]
@TetianaKhomenko I still think the search could do with some optimisation as only exact matches will load results at the top as you will see from my screenshots I would expect partial words to still load at the top of the page.

<img width="1329" alt="Image" src="https://github.com/user-attachments/assets/e3df6498-aa89-4975-97b8-dac8427a057e" />
<img width="1328" alt="Image" src="https://github.com/user-attachments/assets/d0a0c849-b30e-4cb5-9afe-438b5cf309b7" />

**Comment by vhd-lewis** [comment]
@TetianaKhomenko Did you see my above comment?

**Comment by TetianaKhomenko** [comment]
Hi @vhd-lewis! Sorry, I don't get the issue. Could you please rephrase?

**Comment by vhd-lewis** [comment]
So if you compare the 2 search results one is missing the last letter a "T" but I would still expect the partial match to return the "payment link in flight" result first.

**Comment by vhd-lewis** [comment]
@TetianaKhomenko Still had no response?

**Comment by TetianaKhomenko** [comment]
Hi @vhd-lewis, I've tried searching for a partial match and it seems to return all the results. We've recently published improvements for search, so the issue should be fixed.

![Image](https://github.com/user-attachments/assets/70f0b8d1-b8ed-4104-a2b5-5cf85e165d81)

**Comment by vhd-lewis** [comment]
@TetianaKhomenko Looks like its still having the same issue from my perspective. 

![Image](https://github.com/user-attachments/assets/3d50ddb3-87ef-4089-8bb8-7e5d101f16c8)
![Image](https://github.com/user-attachments/assets/5205bc46-a55b-4924-be4f-455029871697)

**Comment by TetianaKhomenko** [comment]
@offtop maybe you can help us here?

**Comment by TetianaKhomenko** [comment]
@vhd-lewis! We've published a new version with improvements for search. You can reopen the ticket if needed

**Comment by vhd-lewis** [comment]
Thanks Tetiana will let you know if this has been resolved or we need to reopen.
