### ISSUE TITLE
Does not generate tests after adding a description and attaching a JIRA task

### ISSUE THREAD

**Issue by apgerasimov** [testomatio/app#1471]
When trying to generate tests in Testomat.io, nothing happens after adding a description and attaching a JIRA task. No errors are shown, and the tests are not created.
In project settings:
Settings > Project > Response Language = Ukrainian

https://github.com/user-attachments/assets/0111f566-873d-4e52-b687-1fa812630bb4

**Comment by DavertMik** [comment]
Should have been fixed & already on production

**Comment by YanaBaranova0909** [comment]
The issue is still present. Please take a look @mykhailiukVitalii 

Env. PROD.  https://app.testomat.io/projects/ibusiness-funding/suite/9f4dabb4------blapi/
When UA language is set up -> and ONLY the Jira issue (totally the same with Suite Description) is linked to the Suite, no tests are suggested, or suggested 2 invalid tests ('popup', ':popup')

Suite Title
`
Відправлення або скасування відправки на модерацію об'єкта BL+API `

Suite Description 

```
### Requirements

* Перша модерація доступна після створення об'єкта, пропозиції та реквізитів (в майбутньому для отримання оплат з бронювання, оплата пакетів)
* Після створення об'єкта виводимо pop-up підказку про обов'язкове створення пропозиції та додавання реквізитів для публікації. Link Користувач бачить пропозиції щодо пошуку, фільтрів та на головній сторінці, а в сам об'єкт потрапляє з картки пропозиції за назвою комплексу
* Повторна модерація після редагування обов'язкових полів: назва, фото. Link
* Під час модерації будь-яке редагування не доступне (виводимо підказку "Ваш об'єкт на модерації" та не даємо відредагувати)
* Під час перегляду об'єкта детально бачимо відсоток заповнення, необхідний для відправки на модерацію Link
* До модерації адміном доступна скасування відправки на модерацію
  Після відправки на модерацію об'єкта можна скасувати модерацію — підтверджуючий pop-up "Ви впевнені, що хочете скасувати відправку на модерацію?"
  Після скасування відправки кнопка редагувати знову клікабельна
  Якщо пропозиція ще не створена та реквізити не заповнені (підприємство не підтверджено, оплата тестова з рахунку-фактури), то об'єкт опубліковується автоматично після завершення модерації та підтвердження всіх етапів

УВАГА!
Зараз ми ще не робимо реквізити, підприємство, тому публікація пропозиції та об'єкту після їх модерації адміном автоматична. Робимо заглушку для модерації підприємства, у майбутньому це частина необхідна для модерації.
```

<img width="2308" height="1300" alt="Image" src="https://github.com/user-attachments/assets/993f361a-b66a-401a-acab-244fae2c3078" />

<img width="2880" height="1282" alt="Image" src="https://github.com/user-attachments/assets/26b92a42-f143-41e8-ba30-8722ab914378" />

https://github.com/user-attachments/assets/c153cd55-d593-4e8b-86d7-e1e1214b911f

**Comment by mykhailiukVitalii** [comment]
Test evidences from the latest `master` branch.
1) Create a new local project with Ukrainian language
2) I added suite with the test description (from comment above)
3) Open Suite and try to use `suggest_new_tests` prompt -> bunch of test by Ukrainian language is suggested 

<img width="1762" height="581" alt="Image" src="https://github.com/user-attachments/assets/89f9c8ec-bbcc-4d5e-89b6-2b6c29f99384" />
<img width="1837" height="615" alt="Image" src="https://github.com/user-attachments/assets/28d40c40-d114-4df0-b697-0c8a82193ceb" />

**Comment by mykhailiukVitalii** [comment]
Next step - deeper testing of product env - `...testomat.io/projects/ibusiness-funding/`
I confirm that the latest updates are not added to the stable version of the program (`app.testomat.io/projects`). That's why we don't see the suggested tests. We need to update the "suggest_new_tests.rb" prompt to the latest version of the master so that this problem doesn't occur.

@DavertMik FYI

As far as I understand, we need to wait for a major update, and then you can test the fix on production `app.testomat.io`
@YanaBaranova0909
